repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
      args: ["--line-length", "130"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args:
          - --add-import
          - from __future__ import annotations
