language: python
cache: pip
dist: xenial
python:
   - "3.6"
   - "3.7"
   - "3.8"
env:
  matrix:
    - export PANDAS_VERSION=0.23.4     && export NUMPY_VERSION=1.19.0
    - export PANDAS_VERSION=0.25.3     && export NUMPY_VERSION=1.19.0
    - export NUMPY_VERSION=1.15.4      && export PANDAS_VERSION=1.0.5
    - export NUMPY_VERSION=1.19.0      && export PANDAS_VERSION=1.0.5
before_install:
  - ls
  # - sudo apt-get update
install: "make"
script:
  # command to run tests
  - make test
after_success:
  - coveralls
# Don't want notifications
notifications:
  email: false
